version: 2
jobs:
  build:
    working_directory: ~/TalentPlusApplication
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx4G
    steps:
      - checkout
      - run: echo "Ashish is working for you 👯"
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Approve license for build tools
          command: (echo y; echo y; echo y; echo y; echo y; echo y) | $ANDROID_HOME/tools/bin/sdkmanager --licenses
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
          destination: test-results/
      - run:
          name: Initial build
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]
            then
              ./gradlew clean assembleRelease --no-daemon --stacktrace
            else
              ./gradlew clean assembleDebug --no-daemon --stacktrace
            fi
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/